name: Check

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:

  install:
    name: "Installing..."
    runs-on: ubuntu-latest
    steps:
      - name: "Using Node.js..."
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: "Caching node modules..."
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "Checking out code..."
        uses: actions/checkout@v2

      - name: "Installing dependencies..."
        run: npm ci

  test-unit:
    name: "Unit tests"
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: "Using Node.js..."
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: "Checking out code..."
        uses: actions/checkout@v2

      - name: "Installing dependencies..."
        run: npm ci

      - name: "Running style checks..."
        run: npm run ci:test:lint

      - name: "Running unit tests..."
        run: npm run ci:test:unit

  test-e2e:
    name: "E2E tests"
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: "Using Node.js..."
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: "Checking out code..."
        uses: actions/checkout@v2

      - name: "Installing dependencies..."
        run: npm ci

      - name: "Running E2E tests..."
        run: npm run ci:test:e2e:record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
